[tool.poetry]
name = "shot-benchmarker"
version = "0.1.0"
description = ""
authors = ["Maxemilian Grönblom <maxemilian.gronblom@abo.fi>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
